version: '3.9'
volumes:
  postgres-db:
services:
  app:
    build: .
    ports:
      - 80:80
    environment:
      POSTGRES_CONNECTION_STRING: "Server=postgres;Database=koncertomaniak;Uid=test;Pwd=test;"
      ALLOW_AUTOMATIC_MIGRATION: true
  postgres:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: koncertomaniak
