version: '3.9'
volumes:
  postgres-db:
  rabbitmq-data:
services:
  app:
    build: .
    ports:
      - 80:80
    environment:
      POSTGRES_CONNECTION_STRING: "Server=postgres;Database=koncertomaniak;Uid=test;Pwd=test;"
      ALLOW_AUTOMATIC_MIGRATION: true
  postgres:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: koncertomaniak
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-data:/var/log/rabbitmq/