on:
  push:
jobs: 
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run docker-compose stack
        run: docker compose -f docker-compose.test.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Setup .NET SDK
        run: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'
      - name: Restore solution
        run: dotnet restore
      - name: Run dev_tools.sh
        run: sh scripts/dev_tools.sh
      - name: Run migrations
        run: sh scripts/migration.sh
      - name: Build solution
        run: dotnet build --no-restore
      - name: Test solution
        run: dotnet test --no-restore --no-build -e ASPNETCORE_ENVIRONMENT='test'
        with:
          POSTGRES_CONNECTION_STRING: "Server=postgres;Database=koncertomaniak;Uid=test;Pwd=test;"
          RABBITMQ_HOST: "rabbitmq"
          RABBITMQ_USERNAME: "root"
          RABBITMQ_PASSWORD: "test"
          AUTH_MODULE_ENABLED: "true"